# Generated by Django 3.0.5 on 2020-05-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0002_auto_20200530_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Female', max_length=6),
            preserve_default=False,
        ),
    ]
