# Generated by Django 3.0.5 on 2020-05-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0005_animal_enclosure'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
