# Generated by Django 3.0.5 on 2020-05-31 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0010_auto_20200531_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalreport',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
