# Generated by Django 3.0.5 on 2020-05-31 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0011_auto_20200531_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalreport',
            old_name='report',
            new_name='content',
        ),
    ]
