# Generated by Django 3.2 on 2021-06-18 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0016_auto_20210617_2133'),
        ('zoo', '0016_auto_20210618_0748'),
    ]

    operations = [
    ]
