# Generated by Django 3.2 on 2021-06-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0017_merge_0016_auto_20210617_2133_0016_auto_20210618_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
